### PR TITLE
Fix jdc fallback

### LINKED ISSUE #466: JDC Fallback broken
This started after we merged [https://github.com/stratum-mining/sv2-apps/pull/452](https://github.com/stratum-mining/sv2-apps/pull/452), which included cleanup of the status main loop.

Even before this cleanup, the current fallback logic worked by re-initializing the channel manager, upstream, JD, and downstream server effectively starting fresh on each fallback. However, prior to the cleanup, while we did spawn a new `channel_manager`, the downstream server was started using an old snapshot of the channel manager (see [https://github.com/stratum-mining/sv2-apps/blob/365e1767c71c31843af471fdd70d7dfc771d793e/miner-apps/jd-client/src/lib/mod.rs#L541](https://github.com/stratum-mining/sv2-apps/blob/365e1767c71c31843af471fdd70d7dfc771d793e/miner-apps/jd-client/src/lib/mod.rs#L541)).

Because of this, the downstream server was initialized with an outdated channel manager snapshot, meaning it already had a template and `prevhash`, rather than starting with the new `CoinbaseConstraints`. Currently, this behavior is no longer part of the flow we no longer use an old snapshot of the channel manager to spawn the downstream server. Instead, we use a fresh instance, which does not have a template or `prevhash` until they are provided by the template provider.

For some reason, we are not receiving the template and `prevhash` immediately after sending `CoinbaseConstraints`.

Adding logs for reference to verify that, after sending new `CoinbaseConstraints`, the template and `prevhash` are not received immediately.

```rust
2026-04-29T10:48:35.026636Z ERROR jd_client_sv2::io_task: Reader error error=SocketClosed
2026-04-29T10:48:35.026702Z DEBUG stratum_apps::fallback_coordinator: FallbackHandler: done called
2026-04-29T10:48:35.026776Z  WARN jd_client_sv2::io_task: Reader task exited.
2026-04-29T10:48:35.026918Z  WARN jd_client_sv2::io_task: Outbound channel closed
2026-04-29T10:48:35.026946Z DEBUG stratum_apps::fallback_coordinator: FallbackHandler: done called
2026-04-29T10:48:35.026963Z  WARN jd_client_sv2::io_task: Writer task exited.
2026-04-29T10:48:35.026961Z ERROR jd_client_sv2::io_task: Reader error error=SocketClosed
2026-04-29T10:48:35.027012Z DEBUG stratum_apps::fallback_coordinator: FallbackHandler: done called
2026-04-29T10:48:35.027032Z  WARN jd_client_sv2::io_task: Reader task exited.
2026-04-29T10:48:35.027155Z  WARN jd_client_sv2::io_task: Outbound channel closed
2026-04-29T10:48:35.027197Z DEBUG stratum_apps::fallback_coordinator: FallbackHandler: done called
2026-04-29T10:48:35.027218Z  WARN jd_client_sv2::io_task: Writer task exited.
2026-04-29T10:48:35.027224Z ERROR jd_client_sv2::upstream: Upstream: error handling pool message. error=JDCError { kind: ChannelErrorReceiver(RecvError), action: Fallback, _owner: PhantomData<jd_client_sv2::error::Upstream> }
2026-04-29T10:48:35.027272Z  WARN jd_client_sv2::upstream: Upstream::handle_pool_message_frame requested fallback error_kind=ChannelErrorReceiver(RecvError)
2026-04-29T10:48:35.027331Z  WARN jd_client_sv2::upstream: Upstream: unified message loop exited.
2026-04-29T10:48:35.027358Z DEBUG stratum_apps::fallback_coordinator: FallbackHandler: done called
2026-04-29T10:48:35.027389Z  WARN jd_client_sv2: Upstream/Job Declarator connection dropped — attempting reconnection...
2026-04-29T10:48:35.027408Z  INFO jd_client_sv2::channel_manager: Channel Manager: fallback triggered, resetting state
2026-04-29T10:48:35.027437Z DEBUG stratum_apps::fallback_coordinator: FallbackCoordinator: triggering fallback
2026-04-29T10:48:35.027454Z  INFO jd_client_sv2::job_declarator: Job Declarator: fallback triggered
2026-04-29T10:48:35.027484Z  WARN jd_client_sv2::job_declarator: JobDeclarator: unified message loop exited.
2026-04-29T10:48:35.027500Z DEBUG stratum_apps::fallback_coordinator: FallbackHandler: done called
2026-04-29T10:48:35.027499Z DEBUG stratum_apps::fallback_coordinator: FallbackHandler: done called
2026-04-29T10:48:35.027541Z  INFO jd_client_sv2::channel_manager: Downstream Server: received fallback signal
2026-04-29T10:48:35.027561Z  INFO jd_client_sv2::channel_manager: Downstream server: Unified loop break
2026-04-29T10:48:35.027578Z DEBUG stratum_apps::fallback_coordinator: FallbackHandler: done called
2026-04-29T10:48:35.027657Z DEBUG stratum_apps::fallback_coordinator: FallbackCoordinator: finished waiting for components to complete cleanup
2026-04-29T10:48:35.027811Z  INFO jd_client_sv2: All components finished fallback cleanup
2026-04-29T10:48:35.027847Z  INFO jd_client_sv2: Existing Upstream or JD instance taken out. Preparing fallback.
2026-04-29T10:48:35.027949Z DEBUG stratum_apps::coinbase_output_constraints: Calculated max coinbase output size max_size=31 outputs_count=1
2026-04-29T10:48:35.027991Z DEBUG stratum_apps::coinbase_output_constraints: Calculated max sigops for coinbase max_sigops=0
2026-04-29T10:48:35.028114Z  INFO jd_client_sv2: Attempting to initialize Jd and upstream...
2026-04-29T10:48:35.028145Z  INFO jd_client_sv2: Trying upstream 1 of 1: pool=0.0.0.0:43333, jds=0.0.0.0:43334
2026-04-29T10:48:35.028129Z  INFO bitcoin_core_sv2::template_distribution_protocol::monitors: Received: CoinbaseOutputConstraints: CoinbaseOutputConstraints(coinbase_output_max_additional_size: 31, coinbase_output_max_additional_sigops: 0)
2026-04-29T10:48:35.028161Z DEBUG stratum_apps::fallback_coordinator: FallbackCoordinator: registering component
2026-04-29T10:48:35.028188Z DEBUG bitcoin_core_sv2::template_distribution_protocol::monitors: monitor_incoming_messages() processing message
2026-04-29T10:48:35.028211Z DEBUG bitcoin_core_sv2::template_distribution_protocol::monitors: Received CoinbaseOutputConstraints - max_additional_size: 31, max_additional_sigops: 0
2026-04-29T10:48:35.028234Z DEBUG bitcoin_core_sv2::template_distribution_protocol::handlers: handle_coinbase_output_constraints() called
2026-04-29T10:48:35.028263Z DEBUG bitcoin_core_sv2::template_distribution_protocol::handlers: Cancelling template_ipc_client_cancellation_token
2026-04-29T10:48:35.028265Z  INFO jd_client_sv2::channel_manager: Starting vardiff loop for downstreams
2026-04-29T10:48:35.028287Z DEBUG bitcoin_core_sv2::template_distribution_protocol::handlers: Creating new template IPC client with new constraints
2026-04-29T10:48:35.028305Z  INFO jd_client_sv2::channel_manager: Vardiff update cycle complete
2026-04-29T10:48:35.028311Z DEBUG bitcoin_core_sv2::template_distribution_protocol: new_template_ipc_client() called - max_size: 31, max_sigops: 0
2026-04-29T10:48:35.028355Z DEBUG bitcoin_core_sv2::template_distribution_protocol: Setting block_reserved_weight: 2000
2026-04-29T10:48:35.028374Z DEBUG bitcoin_core_sv2::template_distribution_protocol: Sending createNewBlock request to Bitcoin Core
2026-04-29T10:48:35.028466Z DEBUG bitcoin_core_sv2::template_distribution_protocol::monitors: Interrupting waitNext request
2026-04-29T10:48:35.031005Z DEBUG bitcoin_core_sv2::template_distribution_protocol::handlers: Updated current_template_ipc_client
2026-04-29T10:48:35.031045Z DEBUG bitcoin_core_sv2::template_distribution_protocol::handlers: Created new template_ipc_client_cancellation_token
2026-04-29T10:48:35.031068Z DEBUG bitcoin_core_sv2::template_distribution_protocol::handlers: Waiting for current monitor_ipc_templates() task to finish
2026-04-29T10:48:35.031111Z  WARN bitcoin_core_sv2::template_distribution_protocol::monitors: Exiting mempool change monitoring loop
2026-04-29T10:48:35.031137Z DEBUG bitcoin_core_sv2::template_distribution_protocol::monitors: monitor_ipc_templates() task exiting
2026-04-29T10:48:35.031252Z DEBUG bitcoin_core_sv2::template_distribution_protocol::handlers: Spawning new monitor_ipc_templates() task
2026-04-29T10:48:35.031307Z DEBUG bitcoin_core_sv2::template_distribution_protocol::monitors: monitor_ipc_templates() task started
2026-04-29T10:48:35.031330Z DEBUG bitcoin_core_sv2::template_distribution_protocol::monitors: Creating dedicated blocking_thread_ipc_client for waitNext requests
2026-04-29T10:48:35.031354Z DEBUG bitcoin_core_sv2::template_distribution_protocol: Creating new thread IPC client
2026-04-29T10:48:35.031943Z DEBUG bitcoin_core_sv2::template_distribution_protocol::monitors: monitor_ipc_templates() entering main loop
2026-04-29T10:48:35.031954Z DEBUG bitcoin_core_sv2::template_distribution_protocol::monitors: monitor_ipc_templates() loop iteration start
2026-04-29T10:48:36.029109Z  INFO jd_client_sv2: Upstream previously marked as malicious, skipping initial attempt warnings.
2026-04-29T10:48:36.029162Z ERROR jd_client_sv2: All upstreams failed after 3 retries each
2026-04-29T10:48:36.029182Z ERROR jd_client_sv2: Failed to initialize upstream: CouldNotInitiateSystem
2026-04-29T10:48:36.029195Z  INFO jd_client_sv2: Fallback to solo mining mode
2026-04-29T10:48:36.029216Z  WARN jd_client_sv2::channel_manager: Waiting for initial template and prevhash from Template Provider...
2026-04-29T10:48:36.129606Z  WARN jd_client_sv2::channel_manager: Waiting for initial template and prevhash from Template Provider...
2026-04-29T10:48:36.230952Z  WARN jd_client_sv2::channel_manager: Waiting for initial template and prevhash from Template Provider...
```

### PR DESCRIPTION
**Pull request by Shourya742**
closes: #466 

This PR ensures that bitcoin-core-sv2 sends the template and prevhash as soon as it receives `CoinbaseConstraint`. At the same time, it ensures that the downstream server responds to the fallback handler and spawns in a separate thread so it doesn’t block the main thread from handling termination signals.

### CODE REVIEW

**Comment by Shourya742** [comment]
JDC solo mining is mostly fixed now. I still need to investigate why the integration tests are failing and implement an IT-specific fallback for JDC. I’ll keep iterating on this.

cc: @plebhash , feel free to suggest changes in the meantime.

**Comment by plebhash** [comment]
we should replace a1d85b713479dd429e7ffa32d20253aebb4b0667 with 7addd2deeb6065cc1e6d1fab6de823a151888f1a, which contains a more comprehensive fix for the issue described here https://github.com/stratum-mining/sv2-apps/issues/466#issuecomment-4346397055

File: miner-apps/jd-client/src/lib/mod.rs [hunk 1]
```diff
@@ -323,21 +323,28 @@ impl JobDeclaratorClient {
...
+                        *config.listening_address(),
+                        task_manager,
+                        cancellation_token,
+                        fallback_coordinator,
+                        downstream_to_channel_manager_sender,
+                        config.supported_extensions().to_vec(),
+                        config.required_extensions().to_vec(),
+                    )
+                    .await;
+            }
```
Comment (plebhash) [inline miner-apps/jd-client/src/lib/mod.rs:389]:
```suggestion
            async move {
                if let Err(e) = initial_channel_manager
                    .start_downstream_server(
                        *config.authority_public_key(),
                        *config.authority_secret_key(),
                        config.cert_validity_sec(),
                        *config.listening_address(),
                        task_manager,
                        cancellation_token,
                        fallback_coordinator,
                        downstream_to_channel_manager_sender,
                        config.supported_extensions().to_vec(),
                        config.required_extensions().to_vec(),
                    )
                    .await {
                        tracing::error!(?e, "Downstream server task exited with error");
                        cancellation_token.cancel();
                    }
            }
```

**Comment by plebhash** [comment]
`jdc_solo_mining_with_bitcoin_core_ipc` is hanging on `info!("Waiting for BitcoinCoreSv2TDP dedicated thread to shutdown...")` because this PR moved `start_downstream_server(...)` into a `TaskManager` task

That changed shutdown scheduling enough to expose a pre-existing race: 

`JobDeclaratorClient::start` can now reach the blocking `BitcoinCoreSv2TDP` thread `join()` before the shutdown propagation task spawned inside `connect_to_bitcoin_core(...)` has cancelled the token that stops that thread.


---

commit b254a4c8c49df38d2bb6611cca2c62b83c32dc08 is adding an explicit call to `bitcoin_core_sv2_cancellation_token.cancel()` on the shutdown phase of `JobDeclaratorClient::start` (after the main `loop` hits `break`)

commit 2c3743c2b4b713ff0f6421950b72f7b66b040ce0 does the same to Pool... even though this hasn't been an issue there yet, this makes the pattern explicit and enforces the intended shutdown ordering, potentially saving us from future headaches

**Comment by plebhash** [comment]
while doing some manual testing with `sv2-tp` instead of IPC, I noticed some extra faulty behavior (that maybe wasn't on our radar up until now)

when I kill Pool/JDS to trigger fallback, JDC never falls back to solo... it simply shuts down:
```
2026-04-29T20:27:13.128652Z  INFO jd_client_sv2::template_receiver::sv2_tp::message_handler: Received: SetupConnectionSuccess(used_version: 2, flags: 0x00000000)
2026-04-29T20:27:13.128662Z  INFO jd_client_sv2::template_receiver::sv2_tp: Handshake with upstream completed successfully
2026-04-29T20:27:13.128665Z  INFO jd_client_sv2::template_receiver::sv2_tp: Setup Connection done. connection with template receiver is now done
2026-04-29T20:27:13.128681Z  INFO jd_client_sv2: Sv2 Template Provider setup done
2026-04-29T20:27:13.128762Z  INFO jd_client_sv2: Attempting to initialize upstream...
2026-04-29T20:27:13.128768Z  INFO jd_client_sv2: Trying upstream 1 of 2: pool=127.0.0.1:3333, jds=127.0.0.1:3334
2026-04-29T20:27:13.129976Z  INFO jd_client_sv2::channel_manager: Starting vardiff loop for downstreams
2026-04-29T20:27:13.130016Z  INFO jd_client_sv2::channel_manager: Vardiff update cycle complete
2026-04-29T20:27:13.157629Z  INFO jd_client_sv2::channel_manager::template_message_handler: Received: NewTemplate(template_id: 4, future_template: true, version: 0x20000000, coinbase_tx_version: 0x00000002, coinbase_prefix: B0255(03f9730e00), coinbase_tx_input_sequence: 0xfffffffe, coinbase_tx_value_remaining: 314399360, coinbase_tx_outputs_count: 1, coinbase_tx_outputs: B064K(0000000000000000266a24aa21a9ed70f087abbab5e63b3c6015f046993bbbbf5375191b012ea18cb59814dc070641), coinbase_tx_locktime: 947192, merkle_path: Seq0255<len=12: [4af128fb4dd5fb6b71b2b9d4ff78d6a1831ae815bc2efb94a5ca9f60fd4ebd58, c8a15ad9c463db2b0ea0398d82c231fd722dfdf890a260c6fe4eca44cacb9acd, ... , 3c04bec60adcc58781f50ccca7e362ce4a41c00d189acc0734480bed02332c7f, 75ff73f4c7724ebab86c2a5c1e3ccd3972f9f631c2caffcce17973ca081d670d])
2026-04-29T20:27:13.157732Z  INFO jd_client_sv2::channel_manager::template_message_handler: Received: SetNewPrevHash { template_id: 4, prev_hash: U256(00000000000000000001107c8a6f549581a9ea2d56e855fedcff87d409cf0ed2), header_timestamp: 1777494433, n_bits: 0x17021369, target: U256(0000000000000000000213690000000000000000000000000000000000000000) }
2026-04-29T20:27:14.130815Z  INFO jd_client_sv2: Connection attempt 1/3...
2026-04-29T20:27:14.130837Z  INFO jd_client_sv2: Upstream connection in-progress at initialize single
2026-04-29T20:27:14.131046Z ERROR jd_client_sv2: Upstream and JDS connection terminated
2026-04-29T20:27:15.133127Z  WARN jd_client_sv2: Attempt 1/3 failed for pool=127.0.0.1:3333, jds=127.0.0.1:3334: Io(Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })
2026-04-29T20:27:15.133152Z  INFO jd_client_sv2: Connection attempt 2/3...
2026-04-29T20:27:15.133157Z  INFO jd_client_sv2: Upstream connection in-progress at initialize single
2026-04-29T20:27:15.133327Z ERROR jd_client_sv2: Upstream and JDS connection terminated
2026-04-29T20:27:16.134654Z  WARN jd_client_sv2: Attempt 2/3 failed for pool=127.0.0.1:3333, jds=127.0.0.1:3334: Io(Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })
2026-04-29T20:27:16.134680Z  INFO jd_client_sv2: Connection attempt 3/3...
2026-04-29T20:27:16.134687Z  INFO jd_client_sv2: Upstream connection in-progress at initialize single
2026-04-29T20:27:16.134853Z ERROR jd_client_sv2: Upstream and JDS connection terminated
2026-04-29T20:27:17.136931Z  WARN jd_client_sv2: Attempt 3/3 failed for pool=127.0.0.1:3333, jds=127.0.0.1:3334: Io(Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })
2026-04-29T20:27:17.136955Z  WARN jd_client_sv2: Max retries reached for pool=127.0.0.1:3333, jds=127.0.0.1:3334, moving to next upstream
2026-04-29T20:27:17.136960Z  INFO jd_client_sv2: Trying upstream 2 of 2: pool=75.119.150.111:3333, jds=75.119.150.111:3334
2026-04-29T20:27:18.139056Z  INFO jd_client_sv2: Connection attempt 1/3...
2026-04-29T20:27:18.139078Z  INFO jd_client_sv2: Upstream connection in-progress at initialize single
2026-04-29T20:27:18.361386Z  INFO jd_client_sv2::upstream: Connected to upstream at 75.119.150.111:3333
2026-04-29T20:27:18.615696Z  INFO jd_client_sv2: Upstream connection done at initialize single
2026-04-29T20:27:18.615715Z  INFO jd_client_sv2::job_declarator: Connecting to JD Server at 75.119.150.111:3334
2026-04-29T20:27:18.625130Z ERROR jd_client_sv2::io_task: Reader error error=SocketClosed
2026-04-29T20:27:18.625138Z  WARN jd_client_sv2::io_task: Reader task exited.
2026-04-29T20:27:18.625145Z  WARN jd_client_sv2::io_task: Outbound channel closed
2026-04-29T20:27:18.625147Z  WARN jd_client_sv2::io_task: Writer task exited.
2026-04-29T20:27:18.836032Z  INFO jd_client_sv2::job_declarator: Connection established with JD Server at 75.119.150.111:3334 in mode: JDMode { inner: 2, config_mode: FullTemplate }
2026-04-29T20:27:19.060212Z  INFO jd_client_sv2::upstream: Upstream: initiating SV2 handshake...
2026-04-29T20:27:19.060227Z ERROR jd_client_sv2::upstream: Failed to send `SetupConnection` frame to upstream e=SendError(..)
2026-04-29T20:27:19.060231Z ERROR jd_client_sv2::upstream: Upstream: connection setup failed. error=JDCError { kind: ChannelErrorSender, action: Fallback, _owner: PhantomData<jd_client_sv2::error::Upstream> }
2026-04-29T20:27:19.060249Z  WARN jd_client_sv2::upstream: Upstream::setup_connection requested fallback error_kind=ChannelErrorSender
2026-04-29T20:27:19.060258Z  INFO jd_client_sv2::job_declarator: Sending SetupConnection to JDS at 75.119.150.111:3334
2026-04-29T20:27:19.060272Z  INFO jd_client_sv2: Monitoring server: fallback triggered.
2026-04-29T20:27:19.060275Z  INFO stratum_apps::monitoring::http_server: Monitoring server received shutdown signal, stopping...
2026-04-29T20:27:19.060289Z  WARN jd_client_sv2::io_task: Writer task exited.
2026-04-29T20:27:19.060325Z ERROR jd_client_sv2::template_receiver::sv2_tp: TemplateReceiver template provider handler failed: JDCError { kind: ChannelErrorReceiver(RecvError), action: Shutdown, _owner: PhantomData<jd_client_sv2::error::TemplateProvider> }
2026-04-29T20:27:19.060330Z  WARN jd_client_sv2::template_receiver::sv2_tp: TemplateReceiver::handle_template_provider_message requested shutdown error_kind=ChannelErrorReceiver(RecvError)
2026-04-29T20:27:19.060334Z  WARN jd_client_sv2::template_receiver::sv2_tp: TemplateReceiver: unified message loop exited.
2026-04-29T20:27:19.060332Z  WARN jd_client_sv2::io_task: Reader task exited.
2026-04-29T20:27:19.060361Z  WARN jd_client_sv2::io_task: Reader task exited.
2026-04-29T20:27:19.060373Z ERROR jd_client_sv2::job_declarator: No handshake response received from Job declarator. error=RecvError
2026-04-29T20:27:19.060426Z  INFO stratum_apps::monitoring::http_server: Monitoring server stopped
2026-04-29T20:27:19.060434Z  INFO jd_client_sv2: Monitoring server task exited and signaled fallback coordinator
2026-04-29T20:27:19.060427Z  WARN jd_client_sv2::job_declarator: JobDeclarator::setup_connection requested fallback error_kind=ChannelErrorSender
2026-04-29T20:27:19.060378Z  INFO jd_client_sv2::channel_manager: Channel Manager: received shutdown signal
2026-04-29T20:27:19.060377Z  WARN jd_client_sv2::io_task: Writer task exited.
2026-04-29T20:27:19.060465Z  INFO jd_client_sv2::channel_manager: Requested allocation of 2 mining job tokens to JDS
2026-04-29T20:27:19.060501Z  INFO jd_client_sv2: Spawning status listener task...
2026-04-29T20:27:19.060512Z  WARN jd_client_sv2: Graceful shutdown: waiting 5 seconds for tasks to finish
2026-04-29T20:27:19.060520Z  INFO jd_client_sv2::channel_manager: Required template data received, ready to accept connections
2026-04-29T20:27:19.060525Z  INFO jd_client_sv2::channel_manager: Starting downstream server at 0.0.0.0:34265
2026-04-29T20:27:19.060599Z  INFO jd_client_sv2::channel_manager: Downstream Server: received shutdown signal
2026-04-29T20:27:19.060602Z  INFO jd_client_sv2::channel_manager: Downstream server: Unified loop break
2026-04-29T20:27:19.060607Z  INFO jd_client_sv2: All tasks joined cleanly
2026-04-29T20:27:19.060614Z  INFO jd_client_sv2: JD Client shutdown complete.
2026-04-29T20:27:19.060618Z  INFO jd_client_sv2: JobDeclaratorClient dropped
```

that's because `Sv2Tp` is also "recycled" during fallback, which shouldn't be the case

this was also introduced via #225

0cf16a2d5a1adc04c22f21b009bf626495ec9e05 is addressing that, by:
- renaming`spawn_io_tasks` into `spawn_io_tasks_with_fallback`
- adding a new `spawn_io_tasks` that does not take `FallbackCoordinator`

that way, we can leverage `Sv2Tp` without forcing fallback disconnections on it

with this, instead of shutting down, JDC goes into a similar state to what was reported on #466:
```
2026-04-29T20:51:34.464102Z ERROR jd_client_sv2: Failed to initialize upstream: CouldNotInitiateSystem
2026-04-29T20:51:34.464104Z  INFO jd_client_sv2: Fallback to solo mining mode
2026-04-29T20:51:34.464107Z  INFO jd_client_sv2: Reinitializing monitoring server on http://0.0.0.0:9091
2026-04-29T20:51:34.464193Z  INFO stratum_apps::monitoring::http_server: Starting monitoring server on http://0.0.0.0:9091
2026-04-29T20:51:34.464200Z  WARN jd_client_sv2::channel_manager: Waiting for initial template and prevhash from Template Provider...
2026-04-29T20:51:34.464201Z  INFO stratum_apps::monitoring::http_server: Cache refresh interval: 15s
2026-04-29T20:51:34.464619Z  INFO stratum_apps::monitoring::http_server: Swagger UI available at http://0.0.0.0:9091/swagger-ui
2026-04-29T20:51:34.464628Z  INFO stratum_apps::monitoring::http_server: Prometheus metrics available at http://0.0.0.0:9091/metrics
2026-04-29T20:51:34.565815Z  WARN jd_client_sv2::channel_manager: Waiting for initial template and prevhash from Template Provider...
2026-04-29T20:51:34.667868Z  WARN jd_client_sv2::channel_manager: Waiting for initial template and prevhash from Template Provider...
2026-04-29T20:51:34.769924Z  WARN jd_client_sv2::channel_manager: Waiting for initial template and prevhash from Template Provider...
2026-04-29T20:51:34.871989Z  WARN jd_client_sv2::channel_manager: Waiting for initial template and prevhash from Template Provider...
...
```

but that's because `sv2-tp` follows a similar design flaw as described in https://github.com/stratum-mining/sv2-apps/issues/466#issuecomment-4346397055

it was reported here: https://github.com/stratum-mining/sv2-tp/issues/99

**Comment by plebhash** [comment]
with:
- 7addd2deeb6065cc1e6d1fab6de823a151888f1a doing adaptations to `bitcoin_core_sv2` (replacing a1d85b713479dd429e7ffa32d20253aebb4b0667)
- b254a4c8c49df38d2bb6611cca2c62b83c32dc08 fixing `BitcoinCoreSv2TDP` shutdown ordering on JDC (plus 2c3743c2b4b713ff0f6421950b72f7b66b040ce0 for Pool)
- 0cf16a2d5a1adc04c22f21b009bf626495ec9e05 introducing `spawn_io_tasks` vs `spawn_io_tasks_with_fallback`

my fork [`2026-04-29-fix-jdc-fallback`](https://github.com/plebhash/sv2-apps/tree/2026-04-29-fix-jdc-fallback) branch is passing all integration tests locally

(I still haven't added new Integration Tests requested https://github.com/stratum-mining/sv2-apps/issues/466#issuecomment-4344854654)

**Comment by plebhash** [comment]
cc948f0207c4f4a37277889ec2dde2df675b9ab0 adds two Integration Tests:
- `jdc_fallback_to_solo_mines_block_with_bitcoin_core_ipc`
- `jdc_fallback_to_solo_mines_block_with_template_provider`

both do the following:
- launch JDC + Pool/JDS
- kill Pool/JDS to trigger fallback
- launch tProxy + minerd
- assert a block was propagated

the difference between both tests is that 
`jdc_fallback_to_solo_mines_block_with_bitcoin_core_ipc` has JDC connected to Bitcoin Core over IPC, while `jdc_fallback_to_solo_mines_block_with_template_provider` has JDC connected to `sv2-tp` doing TDP over TCP

`jdc_fallback_to_solo_mines_block_with_bitcoin_core_ipc` passes locally (on top of the commits listed above), while `jdc_fallback_to_solo_mines_block_with_template_provider` is disabled due to https://github.com/stratum-mining/sv2-tp/issues/99

File: miner-apps/jd-client/src/lib/mod.rs [hunk 2]
```diff
@@ -503,21 +508,28 @@ impl JobDeclaratorClient {
...
+                                    *config.listening_address(),
+                                    task_manager,
+                                    cancellation_token,
+                                    fallback_coordinator,
+                                    downstream_to_channel_manager_sender_new,
+                                    config.supported_extensions().to_vec(),
+                                    config.required_extensions().to_vec(),
+                                )
+                                .await;
+                        }
```
Comment (plebhash) [inline miner-apps/jd-client/src/lib/mod.rs:591]:
```suggestion
                        async move {
                            if let Err(e) = channel_manager
                                .start_downstream_server(
                                    *config.authority_public_key(),
                                    *config.authority_secret_key(),
                                    config.cert_validity_sec(),
                                    *config.listening_address(),
                                    task_manager,
                                    cancellation_token,
                                    fallback_coordinator,
                                    downstream_to_channel_manager_sender_new,
                                    config.supported_extensions().to_vec(),
                                    config.required_extensions().to_vec(),
                                )
                                .await {
                                       tracing::error!(?e, "Downstream server task exited with error");
                                       cancellation_token.cancel();
                                }
                        }
```

**Comment by Shourya742** [comment]
> with:
> 
> * [7addd2d](https://github.com/stratum-mining/sv2-apps/commit/7addd2deeb6065cc1e6d1fab6de823a151888f1a) doing adaptations to `bitcoin_core_sv2` (replacing [a1d85b7](https://github.com/stratum-mining/sv2-apps/commit/a1d85b713479dd429e7ffa32d20253aebb4b0667))
> * [b254a4c](https://github.com/stratum-mining/sv2-apps/commit/b254a4c8c49df38d2bb6611cca2c62b83c32dc08) fixing `BitcoinCoreSv2TDP` shutdown ordering on JDC (plus [2c3743c](https://github.com/stratum-mining/sv2-apps/commit/2c3743c2b4b713ff0f6421950b72f7b66b040ce0) for Pool)
> * [0cf16a2](https://github.com/stratum-mining/sv2-apps/commit/0cf16a2d5a1adc04c22f21b009bf626495ec9e05) introducing `spawn_io_tasks` vs `spawn_io_tasks_with_fallback`
> 
> my fork [`2026-04-29-fix-jdc-fallback`](https://github.com/plebhash/sv2-apps/tree/2026-04-29-fix-jdc-fallback) branch is passing all integration tests locally
> 
> (I still haven't added new Integration Tests requested [#466 (comment)](https://github.com/stratum-mining/sv2-apps/issues/466#issuecomment-4344854654))

I did take the 1st and 2nd, and modified the 3rd to remove duplication.

**Comment by Shourya742** [comment]
Added last set of commits to remove unwraps from start and making sure remove downstream not called when undergoing a fallback or shutdown (as the object will deallocated anyway)

**Comment by GitGab19** [comment]
How is 14ba0f2685f12098dccb4a77d4a98ff7be424018 related to the issue we're trying to solve here?

**Comment by Shourya742** [comment]
> How is [14ba0f2](https://github.com/stratum-mining/sv2-apps/commit/14ba0f2685f12098dccb4a77d4a98ff7be424018) related to the issue we're trying to solve here?

We were panicking in those scenarios, and during fallback we weren’t initiating the correct cancellation token. Now we are, so instead of abrupt panics, we shut down gracefully with a clean slate.

**Comment by GitGab19** [comment]
Also, why do we still have older commits (like af3204b7d7106d212ba0cc383d9cddbb563559a7) which should have been replaced by other commits as suggested by [this comment](https://github.com/stratum-mining/sv2-apps/pull/467#issuecomment-4347633787)?

**Comment by Shourya742** [comment]
> Also, why do we still have older commits (like [af3204b](https://github.com/stratum-mining/sv2-apps/commit/af3204b7d7106d212ba0cc383d9cddbb563559a7)) which should have been replaced by other commits as suggested by [this comment](https://github.com/stratum-mining/sv2-apps/pull/467#issuecomment-4347633787)?

I missed it, thanks will remove.

**Comment by GitGab19** [comment]
> > How is [14ba0f2](https://github.com/stratum-mining/sv2-apps/commit/14ba0f2685f12098dccb4a77d4a98ff7be424018) related to the issue we're trying to solve here?
> 
> We were panicking in those scenarios, and during fallback we weren’t initiating the correct cancellation token. Now we are, so instead of abrupt panics, we shut down gracefully with a clean slate.

When you say we were panicking you mean we were panicking for real on fallback? Did you observe it? Why was CI passing according to @plebhash comment though?

**Comment by Shourya742** [comment]
> > > How is [14ba0f2](https://github.com/stratum-mining/sv2-apps/commit/14ba0f2685f12098dccb4a77d4a98ff7be424018) related to the issue we're trying to solve here?
> > 
> > 
> > We were panicking in those scenarios, and during fallback we weren’t initiating the correct cancellation token. Now we are, so instead of abrupt panics, we shut down gracefully with a clean slate.
> 
> When you say we were panicking you mean we were panicking for real on fallback? Did you observe it? Why was CI passing according to @plebhash comment though?

Again, it’s a rare occurrence (e.g., failure to initialize `ChannelManager` or failure to bind to a port), and since we’re touching cancellation tokens, it makes sense to add them as a safeguard.

**Comment by GitGab19** [comment]
Another thing, in the [same comment](https://github.com/stratum-mining/sv2-apps/pull/467#issuecomment-4347633787) @plebhash was suggesting to take https://github.com/stratum-mining/sv2-apps/commit/2c3743c2b4b713ff0f6421950b72f7b66b040ce0 to fix the issue on the Pool, why isn't it here?

**Comment by Shourya742** [comment]
We have it here: 70cea58a28251b6cc20f6546a248184b4e672eb9, with rebase the commit hash changes.

**Comment by GitGab19** [comment]
Please look at the commit I linked (https://github.com/stratum-mining/sv2-apps/commit/2c3743c2b4b713ff0f6421950b72f7b66b040ce0), it's called `Pool explicitly triggers bitcoin_core_sv2_cancellation_token on shutdown` and touches the Pool, not `bitcoin_core_sv2` as the one you linked.

**Comment by Shourya742** [comment]
Oh!! I didn't took the pool commit, let me do that. Thanks

**Comment by plebhash** [comment]
@Shourya742 can we replace fd46a97 in favor of b69530f?

it's essentially the same fix with some refinements

fd46a97 still leaves room for subtle races around the lifecycle of `self.current_template_ipc_client`

b69530f scopes `waitNext`/fetch/interrupt operations to the monitor's own template IPC client instead of rereading `self.current_template_ipc_client`.

**Comment by Shourya742** [comment]
> @Shourya742 can we replace [fd46a97](https://github.com/stratum-mining/sv2-apps/commit/fd46a971f30632769ad7132e3fc10a5f5af5d195) in favor of [b69530f](https://github.com/stratum-mining/sv2-apps/commit/b69530f254d96e6f566b5520e6ad5add28bc19f8)?
> 
> it's essentially the same fix with some refinements
> 
> [fd46a97](https://github.com/stratum-mining/sv2-apps/commit/fd46a971f30632769ad7132e3fc10a5f5af5d195) still leaves room for subtle races around the lifecycle of `self.current_template_ipc_client`
> 
> [b69530f](https://github.com/stratum-mining/sv2-apps/commit/b69530f254d96e6f566b5520e6ad5add28bc19f8) scopes `waitNext`/fetch/interrupt operations to the monitor's own template IPC client instead of rereading `self.current_template_ipc_client`.

Sure, doing it now.

**Review by plebhash — APPROVED** [review]
approving this

with regards to [backporting to v0.3.x](https://github.com/stratum-mining/sv2-apps/issues/466#issuecomment-4344811858), the steps forward are:
- create a new `release/v0.3.5` branch on top of `release/v0.3.4`
- apply the patches of `jd_client_sv2` and `bitcoin_core_sv2` crates 

I already created [`release/v0.3.5`](https://github.com/stratum-mining/sv2-apps/tree/release/v0.3.5) and cherry-picked b69530f254d96e6f566b5520e6ad5add28bc19f8 from this PR into `release/v0.3.5`, which solves the patch on `bitcoin_core_sv2`

unfortunately we cannot blindly cherry-pick JDC commits from this PR, because JDC on `main` has already drifted substantially from `release/v0.3.4`

so we need a dedicated commit on `release/v0.3.5`, doing similar JDC adaptations that were done here

assuming the JDC patches won't go major changes before merging, this commit might do the job: e299a0b1af2a7a314e55081bc981e37df39bdec0

@Shourya742  can you have a look at e299a0b1af2a7a314e55081bc981e37df39bdec0 to make sure it is properly fixing the issues from this PR on the JDC side?

**Review by GitGab19 — APPROVED** [review]
tACK

**Comment by GitGab19** [comment]
> @Shourya742 can you have a look at https://github.com/stratum-mining/sv2-apps/commit/e299a0b1af2a7a314e55081bc981e37df39bdec0 to make sure it is properly fixing the issues from this PR on the JDC side?

@plebhash I just tested `release/v0.3.5` branch, and the fallback works without any issues, so green light from me!
