### PR TITLE
Remove statics from tproxy and jdc

### LINKED ISSUE #430: TranslatorSv2::start() panics on second call due to process-wide OnceLock statics (breaks sequential integration tests)
## Problem

`TPROXY_MODE` and `VARDIFF_ENABLED` are declared as process-wide `static OnceLock<_>` in `miner-apps/translator/src/lib/mod.rs`:

```rust
static TPROXY_MODE: OnceLock<TproxyMode> = OnceLock::new();
static VARDIFF_ENABLED: OnceLock<bool> = OnceLock::new();
```

`TranslatorSv2::start()` initializes them unconditionally on every call:

```rust
TPROXY_MODE
    .set(self.config.aggregate_channels.into())
    .expect("TPROXY_MODE initialized more than once");
VARDIFF_ENABLED
    .set(self.config.downstream_difficulty_config.enable_vardiff)
    .expect("VARDIFF_ENABLED initialized more than once");
```

`nextest.toml` sets `test-threads = 1`, so all integration tests run sequentially in the **same process**. The first test that calls `start()` on a `TranslatorSv2` sets the `OnceLock`s successfully. Every subsequent test that creates a new `TranslatorSv2` and calls `start()` causes `OnceLock::set()` to return `Err` — the `.expect()` panics. Since `start()` is invoked inside `tokio::spawn`, the panic is silently swallowed, the translator exits immediately, and the test framework only sees a downstream symptom (e.g. "Connection refused" on the monitoring or SV1 port).

## Observed symptom

When running the monitoring integration tests with `--test-threads=1`, the first tProxy test passes and the remaining 9 fail with "Connection refused" on the monitoring endpoint. There are 10 tProxy tests total, producing a consistent 10/9 pass/fail split. Confirmed reproducible on `3773dd5` (upstream main before PR #373).

## Fix

`TPROXY_MODE` and `VARDIFF_ENABLED` should not be process-wide singletons. Options:

1. **Make them instance fields on `TranslatorSv2`** (preferred) — remove the statics, store the values in the struct, and pass them through to callers.
2. **Use `get_or_init` everywhere instead of `set` + `expect`** — this silently ignores the second initialization, which is safe if all instances are configured identically, but masks misconfiguration.

Option 1 is the correct fix as it allows multiple `TranslatorSv2` instances with different configs to coexist in the same process (required for integration tests and any future multi-instance deployment).

### PR DESCRIPTION
**Pull request by Shourya742**
This PR removes the use of static variables that were previously used to specify the operating mode (in JDC: `FullTemplate` / `CoinbaseOnly` / `SoloMining`, and in Tproxy: `Aggregated` / `NonAggregated`). While static approach works fine in production where a single binary simulates the process, it does not work well in integration tests (IT), where these components are used as libraries. In such cases, the test harness is built once, and static global variables are placed in the binary’s data section, remaining valid for the entire runtime. However, for testing, we need the ability to change this value dynamically in accordance to start method invocation. Although it is technically possible to mutate these values (as done in JDC), doing so can introduce non-deterministic behavior. When multiple such tasks run in parallel, they may modify the shared state concurrently without proper coordination, leading to unpredictable results.

This PR updates both Tproxy and JDC to eliminate statics and instead initialize the mode locally within the `start` method.

closes: #430

### CODE REVIEW

**Comment by Shourya742** [comment]
I think Gimballock's AI explained the issue here: <https://github.com/stratum-mining/sv2-apps/pull/373#issuecomment-4247996017>

File: miner-apps/jd-client/src/lib/channel_manager/downstream_message_handler.rs
Comment (plebhash) [inline miner-apps/jd-client/src/lib/channel_manager/downstream_message_handler.rs]: 1cd54bb32b4819c816f522000c0f9d84f415a25d makes this doc outdated

Comment (plebhash) [reply miner-apps/jd-client/src/lib/channel_manager/downstream_message_handler.rs]: for some reason my diff suggestion doesn't render properly on github UI, but here's my attempt:

```diff
-    /// - [`RouteMessageTo::Upstream`] → Sends the mining message upstream, unless in
-    ///   [`JdMode::SoloMining`].
+    /// - [`RouteMessageTo::Upstream`] → Forwards mining message upstream. In solo mode,
+    ///   upstream-directed messages should not be produced.
```

ideally this should be squashed into 1cd54bb32b4819c816f522000c0f9d84f415a25d

File: miner-apps/jd-client/src/lib/jd_mode.rs [hunk 1]
```diff
@@ -5,57 +5,75 @@
 //!
 //! Modes are stored in a global [`AtomicU8`] to allow safe concurrent access
 //! across threads.
```
Comment (plebhash) [inline miner-apps/jd-client/src/lib/jd_mode.rs]:
```suggestion
//! Mode state is stored in `JDMode::inner` (`Arc<AtomicU8>`) to allow safe concurrent access
//! across threads.
```

**Comment by plebhash** [comment]
a similar integration test to avoid JDC regressions: ea9e7f3ee63fb48152dbebe0b6f3b9b339a9a08f

**Comment by Shourya742** [comment]
> a similar integration test to avoid JDC regressions: [ea9e7f3](https://github.com/stratum-mining/sv2-apps/commit/ea9e7f3ee63fb48152dbebe0b6f3b9b339a9a08f)

Picked, thanks

File: miner-apps/jd-client/src/lib/jd_mode.rs [hunk 2]
```diff
@@ -3,59 +3,77 @@
 //! This module defines different operating modes for the Job Declarator
 //! and provides atomic accessors for setting and retrieving the current mode.
 //!
-//! Modes are stored in a global [`AtomicU8`] to allow safe concurrent access
+//! MMode state is stored in `JDMode::inner` (`Arc<AtomicU8>`) to allow safe concurrent access
```
Comment (plebhash) [inline miner-apps/jd-client/src/lib/jd_mode.rs]:
```suggestion
//! Mode state is stored in `JDMode::inner` (`Arc<AtomicU8>`) to allow safe concurrent access
```

**Review by plebhash — APPROVED** [review]

File: miner-apps/jd-client/src/lib/jd_mode.rs (hunk 2 above)
Comment (bit-aloo) [reply miner-apps/jd-client/src/lib/jd_mode.rs]: Removed

File: miner-apps/jd-client/src/lib/job_declarator/message_handler.rs [hunk 3]
```diff
@@ -32,16 +30,7 @@ impl HandleCommonMessagesFromServerAsync for JobDeclarator {
...
-        // successful handshake.
-        let jd_mode = match self.mode {
-            ConfigJDCMode::CoinbaseOnly => JdMode::CoinbaseOnly,
-            ConfigJDCMode::FullTemplate => JdMode::FullTemplate,
-            ConfigJDCMode::SoloMining => JdMode::SoloMining,
-        };
-
-        set_jd_mode(jd_mode);
-
+        self.mode.activate();
```
Comment (GitGab19) [inline miner-apps/jd-client/src/lib/job_declarator/message_handler.rs:33]: It's still not clear to me why we need to set JD mode only here, and not while bootstrapping JDC.

Comment (bit-aloo) [reply miner-apps/jd-client/src/lib/job_declarator/message_handler.rs:33]: because its set to SoloMining initially and only change the mode if JDS connects.

File: miner-apps/jd-client/src/lib/jd_mode.rs [hunk 4]
```diff
@@ -3,59 +3,77 @@
...
-            _ => JdMode::SoloMining,
+    /// This activates mode based on config file once
+    /// upstream connection is made.
+    pub fn activate(&self) {
+        match self.config_mode {
+            ConfigJDCMode::CoinbaseOnly => self.set_coinbase_only(),
+            ConfigJDCMode::FullTemplate => self.set_full_template(),
+            ConfigJDCMode::SoloMining => self.set_solo_mining(),
         }
     }
```
Comment (GitGab19) [inline miner-apps/jd-client/src/lib/jd_mode.rs:40]: If this is called only when JDC receives a `SetupConnection.Success` from JDS, why could it lead to setting JDmode to solo mining?

File: miner-apps/jd-client/src/lib/job_declarator/message_handler.rs (hunk 3 above)
Comment (bit-aloo) [reply miner-apps/jd-client/src/lib/job_declarator/message_handler.rs:33]: We will change this behavior soon....

File: miner-apps/jd-client/src/lib/jd_mode.rs (hunk 4 above)
Comment (bit-aloo) [reply miner-apps/jd-client/src/lib/jd_mode.rs:40]: its more about exhaustiveness of enum, we would never really set that, it all be dependent on what mode we add config_mode (which is set via config)

File: miner-apps/translator/src/lib/sv2/channel_manager/channel_manager.rs [hunk 5]
```diff
@@ -120,6 +125,8 @@ impl ChannelManager {
         status_sender: Sender<Status>,
         supported_extensions: Vec<u16>,
         required_extensions: Vec<u16>,
+        tproxy_mode: TproxyMode,
+        #[cfg(feature = "monitoring")] report_hashrate: bool,
```
Comment (GitGab19) [inline miner-apps/translator/src/lib/sv2/channel_manager/channel_manager.rs:166]: why did you call this `report_hashrate` instead of `enable_vardiff`?

Comment (bit-aloo) [reply miner-apps/translator/src/lib/sv2/channel_manager/channel_manager.rs:166]: its only used in monitoring, and there we call it report hashrate. Considering the context is related to report hashrate which would only be used in monitoring.

**Review by GitGab19 — APPROVED** [review]
