### PR TITLE
remove time sensitive assertion from `snapshot_cache::tests::test_snapshot_refresh`

### LINKED ISSUE #301: test `monitoring::snapshot_cache::tests::test_snapshot_refresh` breaking coverage CI
I think the flakiness is coming from the time sensitive assertions that it does on the unit tests.

This is doing an assertion of a 100ms in a CI job under heavy load
https://github.com/stratum-mining/sv2-apps/blob/72cc650870d5483da1eae89cd6800f5637f95320/stratum-apps/src/monitoring/snapshot_cache.rs#L232

The last two times that the CI failed it was in this test:
```bash
test monitoring::snapshot_cache::tests::test_snapshot_refresh ... FAILED

failures:

---- monitoring::snapshot_cache::tests::test_snapshot_refresh stdout ----

thread 'monitoring::snapshot_cache::tests::test_snapshot_refresh' (6277) panicked at src/monitoring/snapshot_cache.rs:232:9:
assertion failed: snapshot.age().unwrap() < Duration::from_millis(100)
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/5fb2ff8611e5a4af4dc85977cfdecfbf3ffa6ade/library/std/src/panicking.rs:689:5
   1: core::panicking::panic_fmt
             at /rustc/5fb2ff8611e5a4af4dc85977cfdecfbf3ffa6ade/library/core/src/panicking.rs:80:14
   2: core::panicking::panic
             at /rustc/5fb2ff8611e5a4af4dc85977cfdecfbf3ffa6ade/library/core/src/panicking.rs:150:5
   3: stratum_apps::monitoring::snapshot_cache::tests::test_snapshot_refresh
             at ./src/monitoring/snapshot_cache.rs:232:9
   4: stratum_apps::monitoring::snapshot_cache::tests::test_snapshot_refresh::{closure#0}
             at ./src/monitoring/snapshot_cache.rs:216:31
   5: <stratum_apps::monitoring::snapshot_cache::tests::test_snapshot_refresh::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/5fb2ff8611e5a4af4dc85977cfdecfbf3ffa6ade/library/core/src/ops/function.rs:250:5
   6: <fn() -> core::result::Result<(), alloc::string::String> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/5fb2ff8611e5a4af4dc85977cfdecfbf3ffa6ade/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    monitoring::snapshot_cache::tests::test_snapshot_refresh
```

see: https://github.com/stratum-mining/sv2-apps/actions/runs/22486794825/job/65138319774
https://github.com/stratum-mining/sv2-apps/actions/runs/22357822442/job/64997474750

### PR DESCRIPTION
**Pull request by lucasbalieiro**
hopefully fix the code coverage CI.

closes #301 

Also took the chance to remove unused API from `MonitoringSnapshot`. 
see: https://github.com/stratum-mining/sv2-apps/pull/302#discussion_r2870138431

### CODE REVIEW

File: stratum-apps/src/monitoring/snapshot_cache.rs [hunk 1]
```diff
@@ -229,7 +229,6 @@ mod tests {
         cache.refresh();
         let snapshot = cache.get_snapshot();
         assert!(snapshot.timestamp.is_some());
-        assert!(snapshot.age().unwrap() < Duration::from_millis(100));
```
Comment (Shourya742) [inline stratum-apps/src/monitoring/snapshot_cache.rs]: What should be the ideal value of this?
