### PR TITLE
Fix/337 move metrics to cache refresh

### LINKED ISSUE #337: fix GaugeVec reset gap in handle_prometheus_metrics
## Context
`handle_prometheus_metrics` in `stratum-apps/src/monitoring/http_server.rs` calls `.reset()` on all `GaugeVec` metrics before repopulating from the snapshot cache:

```rust
// Reset per-channel metrics before repopulating
if let Some(ref metric) = state.metrics.sv2_client_channel_hashrate { metric.reset(); }
// ...
```

This creates a brief window on every `/metrics` request where all label series are absent. It is the root reason `poll_until_metric_gte` is needed in integration tests — without polling, a test can hit `/metrics` during this gap and see the metric missing even though a share was already accepted.

## Goal
Eliminate the reset gap so GaugeVec metrics can be asserted directly (without polling) after the snapshot has refreshed.

## Suggested approach
Instead of `.reset()` + repopulate-all, compute the new label set from the snapshot and:
1. `.set()` all current label combinations
2. `.remove()` only label combinations that are no longer present (stale channels)

This preserves the cardinality-bounding behavior (stale channels are still cleaned up) while eliminating the gap where all labels temporarily disappear.

Related to PR #281.

### PR DESCRIPTION
**Pull request by gimballock**
## Problem

Monitoring integration tests were flaky due to race conditions between metric collection and assertion. The /metrics handler synchronously collected data by acquiring locks on business logic structures, creating two issues:

1. **Test flakiness**: Data could change between scrape and assertion
2. **Production DoS**: Rapid scrapes could block share validation/job distribution

### External Evidence of the Race Condition

**1. Issue #301: CI Flakiness (Reporter: lucasbalieiro)**
Test `monitoring::snapshot_cache::tests::test_snapshot_refresh` was breaking coverage CI:
```
failures:
    monitoring::snapshot_cache::tests::test_snapshot_refresh

thread 'monitoring::snapshot_cache::tests::test_snapshot_refresh' panicked at 
stratum-apps/src/monitoring/snapshot_cache.rs:216:31:
assertion failed: metrics_text.contains(...)
```
CI runs: https://github.com/stratum-mining/sv2-apps/actions/runs/22486794825

**2. Commit ff46a737 by Lucas Balieiro**
```
remove time sensitive assertion from `monitoring::snapshot_cache::tests::test_snapshot_refresh`

this is being removed because it was causing the CI job responsible for 
generating the code coverage to be flaky.

the CI environment has very constrained resources and the test is expecting 
some things to happens in less than 100ms
```
The "fix" was removing timing assertions rather than fixing the root cause.

### Scope: Only Per-Connection/Per-Channel Metrics Affected

**Only GaugeVec metrics with per-channel labels are affected by this race condition.** Simple gauges (totals, uptime) are not affected.

**Affected metrics** (these use `.reset()` + repopulate in the old handler):
- `sv2_client_channel_hashrate{client_id, channel_id, user_identity}`
- `sv2_client_shares_accepted_total{client_id, channel_id, user_identity}`
- `sv2_server_channel_hashrate{channel_id, user_identity}`
- `sv2_server_shares_accepted_total{channel_id, user_identity}`

**Why these specifically**: When a channel disconnects, its label combination becomes stale. The old code called `.reset()` on every `/metrics` request to clean up stale labels, creating a gap where all per-channel metrics temporarily disappear.

**Not affected**: Simple gauges like `sv2_uptime_seconds`, `sv2_clients_total`, `sv2_client_hashrate_total` — these don't need label cleanup and were never reset.

### Recent Commits Amplify the Problem

Share accounting fixes (6994167c) and blocks_found metrics (d3d703ca) keep adding more metric collection code to the handler, making the race window larger.

## Solution

Move gauge updates into the background SnapshotCache refresh task:

1. **Atomic updates**: Snapshot data and Prometheus gauges are now updated together during cache refresh, not on-demand during scrapes
2. **Targeted stale-label removal**: Instead of `.reset()` + repopulate-all, we now `.set()` current labels and `.remove()` only labels that are no longer present
3. **Simplified /metrics handler**: Now just sets uptime gauge, gathers, and encodes — no more label manipulation

The handler's doc comment confirms the fix:
> "Because metric values are always kept in sync with the snapshot data, there is 
> never a gap where label series momentarily disappear. Tests can assert on metrics 
> directly after a cache refresh without polling for transient states."

### Current Branch (with fix)
Monitoring integration tests pass consistently:
```
cargo nextest run -E 'test(monitoring)' --package integration_tests_sv2
PASS [ 17.859s] pool_monitoring_with_sv2_mining_device
PASS [ 14.763s] jd_aggregated_topology_monitoring  
PASS [ 13.687s] pool_and_tproxy_monitoring_with_sv1_miner
```

### Impact Assessment
**Before fix** (evidence from Issue #301 and ff46a737):
- CI failures under load (constrained resources)
- Timing assertions removed to stop CI breakage
- `poll_until_metric_gte` uses 5-second timeout with 100ms polling intervals
- Up to 50 polling attempts per metric assertion

**After fix**:
- Atomic updates eliminate the race window
- Polling now only waits for cache refresh timing (~1s in tests), not race recovery
- **Estimated 5× reduction in retry attempts** (10 vs 50 polls typical)
- CI failures resolved

### Test Infrastructure Evidence
The very existence of `poll_until_metric_gte` in `prometheus_metrics_assertions.rs` demonstrates the problem:
```rust
/// Poll /metrics until metric_name is present with a value >= min...
/// The handler calls .reset() on every /metrics request before repopulating
/// from the cached snapshot, so a label combination is only present when
/// the snapshot contains a non-default value for it.
pub async fn poll_until_metric_gte(...) -> String
```

This polling exists because without atomic updates, metrics could be missing during the reset/repopulate gap.

## Changes

- SnapshotCache now owns PrometheusMetrics and PreviousLabelSets
- refresh() updates snapshot data AND Prometheus gauges atomically
- /metrics handler reduced to: set uptime gauge, gather, encode
- ServerState simplified (no more PreviousLabelSets or Mutex)

Closes #337

### CODE REVIEW

File: docker/Dockerfile [hunk 1]
```diff
@@ -47,8 +47,8 @@ COPY stratum-apps/ stratum-apps/
 RUN echo "Building ${APP}" && \
     case "$APP" in \
         pool_sv2) cargo build --release --manifest-path pool-apps/pool/Cargo.toml --target-dir ./ ;; \
-        jd_client_sv2) cargo build --release --manifest-path miner-apps/jd-client/Cargo.toml --target-dir ./ ;; \
-        translator_sv2) cargo build --release --manifest-path miner-apps/translator/Cargo.toml --target-dir ./ ;; \
+        jd_client_sv2) cargo build --release --manifest-path=miner-apps/jd-client/Cargo.toml --target-dir ./ ;; \
+        translator_sv2) cargo build --release --manifest-path=miner-apps/translator/Cargo.toml --target-dir ./ ;; \
         *) echo "Unknown APP: $APP" && exit 1 ;; \
```
Comment (Shourya742) [inline docker/Dockerfile]: Why this change?

**Review by Shourya742 — COMMENTED** [review]
Can you explain what this PR does?

**Comment by gimballock** [comment]
> Can you explain what this PR does?

Sorry for omitting a decent description, it probably would have gotten attention sooner if I had made it more recognizable, lol.

File: integration-tests/tests/monitoring_integration.rs [hunk 2]
```diff
@@ -103,13 +108,7 @@ async fn pool_and_tproxy_monitoring_with_sv1_miner() {
     // -- tProxy metrics --
     let tproxy_mon = tproxy_monitoring.expect("tproxy monitoring should be enabled");
     assert_api_health(tproxy_mon).await;
-    let tproxy_metrics = poll_until_metric_gte(
-        tproxy_mon,
-        "sv2_server_shares_accepted_total",
-        1.0,
-        std::time::Duration::from_secs(10),
-    )
-    .await;
```
Comment (GitGab19) [inline integration-tests/tests/monitoring_integration.rs:112]: Why aren't we checking `sv2_server_shares_accepted_total` anymore?

File: stratum-apps/src/monitoring/http_server.rs [hunk 3]
```diff
@@ -196,18 +196,21 @@ impl MonitoringServer {
         let has_server = snapshot.server_info.is_some();
         let has_sv2_clients = snapshot.sv2_clients_summary.is_some();
 
-        // Add Sv1 clients source to the cache
+        // Re-create metrics with SV1 enabled
```
Comment (GitGab19) [inline stratum-apps/src/monitoring/http_server.rs]:
```suggestion
        // Create metrics with SV1 monitoring enabled
```

File: stratum-apps/src/monitoring/snapshot_cache.rs [hunk 4]
```diff
@@ -37,16 +37,31 @@
...
+    prometheus_metrics::PrometheusMetrics,
     server::{ServerInfo, ServerMonitoring, ServerSummary},
     sv1::{Sv1ClientInfo, Sv1ClientsMonitoring, Sv1ClientsSummary},
 };
 
+/// Tracks which label combinations were set on the previous refresh so we can
+/// remove only stale series instead of calling `.reset()` (which would create a
+/// gap where all label series momentarily disappear).
+#[derive(Default)]
+struct PreviousLabelSets {
```
Comment (GitGab19) [inline stratum-apps/src/monitoring/snapshot_cache.rs]:
```suggestion
struct PreviousPrometheusLabelSets {
```

File: stratum-apps/src/monitoring/snapshot_cache.rs [hunk 5]
```diff
@@ -63,24 +78,42 @@ pub struct MonitoringSnapshot {
...
+/// snapshot data. This means the `/metrics` handler never needs to compute
+/// values — it only gathers and encodes.
 pub struct SnapshotCache {
     snapshot: RwLock<MonitoringSnapshot>,
     refresh_interval: Duration,
     server_source: Option<Arc<dyn ServerMonitoring + Send + Sync>>,
     sv2_clients_source: Option<Arc<dyn Sv2ClientsMonitoring + Send + Sync>>,
     sv1_clients_source: Option<Arc<dyn Sv1ClientsMonitoring + Send + Sync>>,
+    metrics: Option<PrometheusMetrics>,
+    previous_labels: Mutex<PreviousLabelSets>,
```
Comment (GitGab19) [inline stratum-apps/src/monitoring/snapshot_cache.rs]:
```suggestion
    previous_metrics_labels: Mutex<PreviousLabelSets>,
```

File: stratum-apps/src/monitoring/snapshot_cache.rs [hunk 6]
```diff
@@ -63,24 +78,42 @@ pub struct MonitoringSnapshot {
...
 }
 
 impl Clone for SnapshotCache {
     fn clone(&self) -> Self {
-        // Clone creates a new cache with the same sources and current snapshot
+        // Clone creates a new cache with the same sources and current snapshot.
+        // previous_labels is cloned so the new cache can correctly detect stale
+        // label combinations on its first refresh.
         let current_snapshot = self.snapshot.read().unwrap().clone();
+        let prev = self
```
Comment (GitGab19) [inline stratum-apps/src/monitoring/snapshot_cache.rs]:
```suggestion
        let previous_metrics_labels = self
```

File: stratum-apps/src/monitoring/snapshot_cache.rs [hunk 7]
```diff
@@ -63,24 +78,42 @@ pub struct MonitoringSnapshot {
...
+            .previous_labels
+            .lock()
+            .unwrap_or_else(|e| e.into_inner());
```
Comment (GitGab19) [inline stratum-apps/src/monitoring/snapshot_cache.rs:111]: Is this safe to do?

If so, add a comment explaining why.

File: integration-tests/lib/prometheus_metrics_assertions.rs
Comment (GitGab19) [inline integration-tests/lib/prometheus_metrics_assertions.rs:1]: I’m not sure this is the right behavior. Using `parse_metric_value()` inside `poll_until_metric_gte()` means metric polling now depends only on the first matching series. 

Since we are touching this part now, why not tackling #336 and make polling only label-specific?

File: integration-tests/tests/monitoring_integration.rs (hunk 2 above)
Comment (gimballock) [reply integration-tests/tests/monitoring_integration.rs:112]: Good catch — that assertion was unintentionally dropped while simplifying the test post-race-fix. The Pool poll on sv2_client_shares_accepted_total only synchronizes the Pool's snapshot cache; tProxy is a separate process with its own cache, so its sv2_server_shares_accepted_total needs an independent poll. Restored.

File: stratum-apps/src/monitoring/http_server.rs (hunk 3 above)
Comment (gimballock) [reply stratum-apps/src/monitoring/http_server.rs]: done

File: stratum-apps/src/monitoring/snapshot_cache.rs (hunk 4 above)
Comment (gimballock) [reply stratum-apps/src/monitoring/snapshot_cache.rs]: done

File: stratum-apps/src/monitoring/snapshot_cache.rs (hunk 7 above)
Comment (gimballock) [reply stratum-apps/src/monitoring/snapshot_cache.rs:111]: Yes, it's safe. Added a comment explaining why: the inner sets only track which Prometheus label combinations were populated last refresh — used solely for stale-label removal. The data has no cross-field invariants. Worst-case after recovery is a stale label surviving one cycle or an idempotent remove_label_values call (already logged at debug). Panicking inside Clone would crash the entire monitoring server, which is strictly worse.

File: integration-tests/tests/monitoring_integration.rs (hunk 2 above)
Comment (gimballock) [reply integration-tests/tests/monitoring_integration.rs:112]: Also applied the same fix to `jd_aggregated_topology_monitoring` at L197 — it had the same fetch_metrics → no-poll pattern and would have been susceptible to the same tProxy-cache timing gap. Both topologies now poll tProxy's `sv2_server_shares_accepted_total` consistently.

File: integration-tests/lib/prometheus_metrics_assertions.rs
Comment (gimballock) [reply integration-tests/lib/prometheus_metrics_assertions.rs:1]: I pushed a follow-up commit (888b8542) that addresses both the polling concern and #336 directly: introduces a Metric<'a> selector type with From<&str> for bare names, plus Metric::with_labels(name, &[(k, v), ...]) for label-specific matching. Labels are now order-independent, subset matching is supported, no quote escaping at call sites. All assertion helpers (parse_metric_value, assert_metric_*, poll_until_metric_gte) take impl Into<Metric>, so existing bare-name calls are unchanged.

Let me know if this matches up with what you are looking for.

Comment (GitGab19) [reply integration-tests/lib/prometheus_metrics_assertions.rs:1]: It looks definitely better now, good improvement!

Why not trying to expand a bit more the assertions we have in some tests, with more (key,value) labels?

For example, instead of simply checking the following:
```
let pool_metrics = poll_until_metric_gte(
        pool_mon,
        "sv2_client_shares_accepted_total",
        1.0,
        std::time::Duration::from_secs(10),
    )
.await();
```
we might expand those assertion with:
```
let pool_metrics = poll_until_metric_gte(
    pool_mon,
    Metric::with_labels(
        "sv2_client_shares_accepted_total",
        &[
            ("client_id", "1"),
            ("channel_id", "<expected-channel-id>"),
            ("user_identity", "<expected-user-identity>"),
        ],
    ),
    1.0,
    METRIC_POLL_TIMEOUT,
)
.await;
```

What do you think?

Comment (gimballock) [reply integration-tests/lib/prometheus_metrics_assertions.rs:1]: Pushed — applied your suggestion across tests #1–3 with the actual fixture-known label values verified against /metrics output:
- Test #1: gave the SV2 mining device an explicit user_id so its user_identity label is a meaningful "test-miner" instead of empty.
- Test #2 (pool + tProxy + 1 SV1): asserts on client_id="1", channel_id="2", user_identity="user_identity.miner1" on the pool side and the same user_identity on tProxy's server-side view — surprising find: the SV1 worker name ("miner1") gets suffixed onto tProxy's configured user_identity and propagates all the way upstream. The new selector pins this behavior.
- Test #3 (aggregated, JDC): asserts user_identity="IT-test" on the pool side (JDC's identity) and the same SV1 worker suffix on tProxy.
- Test #4 (block found): kept bare since sv2_client_blocks_found_total is a scalar gauge with no labels; added a comment.

Two interesting observations that fell out:
- The pool reserves channel_id="1" internally and assigns "2" to the first downstream-opened channel. Worth knowing for future test authoring.
- The bare-name form was implicitly accepting any SV1 worker's identity in the pool's view. The labeled form now catches if the SV1 worker name doesn't propagate correctly through tProxy.

Comment (GitGab19) [reply integration-tests/lib/prometheus_metrics_assertions.rs:1]: awesome!

**Review by GitGab19 — APPROVED** [review]
